blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Commmunity Discussion
    url: https://github.com/yoyocubano/akamara_S.U.R.L./discussions
    about: Please ask questions in our discussion forum before opening an issue.
